//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UscWebservices.Weixin.JiaoWu
{
    using System;
    using System.Collections.Generic;
    
    public class V_SYS_UsersInfo
    {
        public System.Guid XTYHID { get; set; }
        public Nullable<System.Guid> YHID { get; set; }
        public Nullable<System.Guid> USERID { get; set; }
        public string YHJB { get; set; }
        public string YHLX { get; set; }
        public string SJBSMC { get; set; }
        public Nullable<System.Guid> YXSID { get; set; }
        public string YXSMC { get; set; }
        public string XM { get; set; }
        public string XB { get; set; }
        public string SJBS { get; set; }
        public string YHJBM { get; set; }
        public string YHLXM { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool IsLockedOut { get; set; }
    }
}
