//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UscWebservices.Weixin.JingPinKeCheng
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string number { get; set; }
        public string logname { get; set; }
        public string password { get; set; }
        public byte user_type { get; set; }
        public string password_src { get; set; }
    }
}
